version: '3'

services:
  client:
    image: distribuidosimage
    tty: true
    
  calculusServer:
    image: distribuidosimage
    tty: true
    ports:
      - "65430:65430"
  
  operationServer:
    image: distribuidosimage
    tty: true
    ports:
      - "65433:65433"
