version: '3'

services:
  client:
    image: distribuidosimage
    volumes:
      - ./scripts:/home/distribuidos/scripts
    tty: true
    
  calculusServer:
    image: distribuidosimage
    volumes:
      - ./scripts:/home/distribuidos/scripts
    tty: true
    expose:
      - "65430"
    command: python3 "serverCalculo.py"
  
  operationServer:
    image: distribuidosimage
    volumes:
      - ./scripts:/home/distribuidos/scripts
    tty: true
    expose:
      - "65433"
    command: python3 "serverOperacion1.py"
    deploy:
      mode: replicated
      replicas: 2
